Fix for calculating the Url Base in a wasm app served in a path diffe…
tpeczek/Blazor.BroadcastChannel pull request #3
Opened 2024-02-13 00:05 UTC by victorperez2911

…rent from the WebSite Root (e.g. using the href attribute element of the index.html base element)

2024-02-14 08:53 UTC, tpeczek requested changes

2024-02-14 08:53 UTC, tpeczek commented on src/Blazor.BroadcastChannel/BroadcastChannelService.cs
> -            _moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>("import", "/_content/Blazor.BroadcastChannel/Blazor.BroadcastChannel.js"));
I've done some testing and it looks that it might be enough to change the path to `"./_content/Blazor.BroadcastChannel/Blazor.BroadcastChannel.js"`. That said, I don't know if I have reproduced your scenario, can you test that approach?

2024-02-14 08:53 UTC, tpeczek commented on src/Blazor.BroadcastChannel/BroadcastChannelService.cs
> +            //_moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>("import", "/_content/Blazor.BroadcastChannel/Blazor.BroadcastChannel.js"));
No need to comment out the code, you can just delete it 😉.

2024-02-14 12:32 UTC, victorperez2911 commented on src/Blazor.BroadcastChannel/BroadcastChannelService.cs
> -            _moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>("import", "/_content/Blazor.BroadcastChannel/Blazor.BroadcastChannel.js"));
The scenario I brought up only occurs after deployment, which makes testing your approach difficult.

Can you publish a pre-release of the package with this change?

2024-02-15 09:52 UTC, tpeczek commented on src/Blazor.BroadcastChannel/BroadcastChannelService.cs
> -            _moduleTask = new(() => jsRuntime.InvokeAsync<IJSObjectReference>("import", "/_content/Blazor.BroadcastChannel/Blazor.BroadcastChannel.js"));
Sure thing, but it may need to wait till weekend.

2024-02-22 11:19 UTC, tpeczek approved these changes

2024-02-22 11:23 UTC, merged